config/routes.rb
Microaccel::Application.routes.draw do

root 'projects#index'

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "users#new", :as => "signup"

resources :projects do
  resources :discussions, :except => [:index]
  resources :pledges
end

resources :users
resources :sessions

get 'tags/:tag', to: 'projects#index', as: :tag

get '/search', to: 'projects#search', as: 'search'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_many :owned_projects, class_name: "Project" 
  has_many :pledges

  has_many :projects, through: :pledges

  has_many :discussions 

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @userprojects = @user.projects
    @userpledges = @user.pledges
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to root_url :notice => "Signed up!"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to projects_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :authentications_attributes, :provider)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

</br>

<div class="FB"><%= link_to "Sign Up with Facebook", auth_at_provider_path(:provider => :facebook) %></div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= @user.email %></br></br>

<h3>Your Projects</h3>
<% @userprojects.each do |p| %>
  <%= p.title %></br>
<% end %></br>

<h3>Your Pledges</h3>
<% @user.pledges.each do |p| %>
  <%= Project.find_by_id(p.id).title unless Project.find_by_id(p.id) == nil%></br>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>