config/routes.rb
Microaccel::Application.routes.draw do

root 'projects#index'

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "users#new", :as => "signup"

resources :projects do
  resources :discussions, :except => [:index]
  resources :pledges
end

resources :users
resources :sessions

get 'tags/:tag', to: 'projects#index', as: :tag

get '/search', to: 'projects#search', as: 'search'

end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  acts_as_taggable

  belongs_to :owner, foreign_key: "user_id"

  has_many :pledges

  has_many :sponsors, through: :pledges, class_name: "User"

  has_many :discussions

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @subtotal = 0
    if params[:tag]
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.all
    end
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    remaining_date
    pledges_so_far

    if current_user
      @pledge = @project.pledges.build
      @discussion = @project.discussions.build
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_url
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url
  end

  def remaining_date
    @days_left = (@project.end_date - @project.start_date).to_i
  end

  def pledges_so_far
    # @total = 0

    # @totalpledges = Project.find(params[:id]).pledges
    # @totalpledges.each do |t|
    #   @total += t.amount_in_cents
    # end

    @total = @project.pledges.sum(:amount_in_cents) 
  end

  def search
    @result = Project.where("title LIKE '%#{params[:s]}%'")
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :user_id, :goal_in_cents, :photo, :start_date, :end_date, :tag_list)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def percentagechecker(project)
    @percent = (project.pledges.sum(:amount_in_cents).to_f/project.goal_in_cents.to_f) *100
    if @percent > 100
      @percent = 100
    else
      @percent
    end
  end
end

app/views/projects/_commentform.html.erb
<h1> Add a Comment </h1>

<% if current_user %>

<%= form_for([@project, @discussion], :remote => true) do |f| %>
  <% if @discussion.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% @discussion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "Comment: " %>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <% else %>
  <p>Please <%= link_to "Log In", new_session_path %> to add a comment.</p>
  <% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %> 
    <%= f.text_field :title, :placeholder => "Title" %>
  </div>
  <div class="field">
    <%= f.label :description %> 
    <%= f.text_area :description, :placeholder => "Description" %>
  </div>
  <div class="field">
    <%= f.label :goal_in_cents %>
    <%= f.number_field :goal_in_cents, :placeholder => "$$$" %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (seperated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <br><%= f.submit %> 
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/projects/_pledgeform.html.erb
<h1> So You Want to Pledge to <br/><strong><%= @project.title %></strong>, eh? </h1>

<% if current_user %>

<%= form_for([@project, @pledge], :remote => true) do |f| %>
  <% if @pledge.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

        <ul>
        <% @pledge.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "Amount to Pledge in Cents" %>
      <%= f.number_field :amount_in_cents %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <% else %>
  <p>Please <%= link_to "Log In", new_session_path %> to pledge.</p>
  <% end %>

app/views/projects/_search.html.erb
<%= @result %>

app/views/projects/_showcomment.html.erb
<p> Comments for <%= @project.title %></p>
<% @project.discussions.each do |d| %>
  <% if d.user !=nil %>
    Contributor: <%= d.user.username %></br>
    <%= d.comment %></br>
    <%= d.created_at %></br>
  <% end %>
<% end %>

app/views/projects/_showpledge.html.erb
<p> Pledges for <%= @project.title %></p>
<% @project.pledges.each do |pledge| %>
  <% if pledge.user !=nil %>
    Contributor: <%= pledge.user.username %></br>
    $<%= (pledge.amount_in_cents.to_f / 100) %></br>
    <%= pledge.created_at %></br>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= link_to "Back to Project", project_path %>

<%= render "form" %>

app/views/projects/index.html.erb
<div class="row" id="showcase"></div>
<!-- <div class="row" id="fill"><div class="leftfill"></div><div class="rightfill"></div></div>
 -->

 <div class="search">
  <%= form_tag("/search", method: "get") do %>
    <%= text_field_tag :s, nil, :placeholder => "Search Projects" %>
    <%= submit_tag("SEARCH") %>
  <% end %>
</div>
</br>
<div class="row">
  <div class="large-12 columns">

<% if current_user %>
  <%= link_to "+ Add New Projects", new_project_url, {:class => "button"} %></br>
<% end %>

<% @projects.each do |project| %>
  <div class="large-4 small-6 columns">
    <div class="panel">
      <h4><%= link_to project.title, project_url(project) %></h4>
      <div class="showcaseimg"><%= link_to (image_tag project.photo), project_url(project) %></br></br></div>
      <%= project.description %></br>
      <h6>Goal: <strong>$<%= (project.goal_in_cents.to_f / 100).round %></strong></h6>
      <hr>
      <strong><%= (project.end_date - project.start_date).to_i %></strong> Days Left</br>
      Amount Raised So Far: <strong>$<%= ((project.pledges.sum(:amount_in_cents).to_f) /100).round %></strong></br>
      Funded: <strong><%= ((project.pledges.sum(:amount_in_cents).to_f/project.goal_in_cents.to_f) *100).round %>%</strong>
      <br/>
      <br/>
      <div class="progress small-12 success round">
        <span class="meter" style="width:<%= percentagechecker(project) %>%"></span>
      </div>

      Categories: <%= raw project.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>

      <hr>
    </div>
  </div>

<% end %>

  </div>
</div>

app/views/projects/new.html.erb
<h1> Start a New Project</h1>

<%= link_to "Back to All Projects", projects_path %>
<br></br>
<%= render "form" %>

app/views/projects/search.html.erb
<h1> Search Results </h1>
<hr>

<% @result.each do |r| %>
  <h2><%= r.title %></h2></br>
  <%= image_tag r.photo %></br>
  <%= r.description %></br>
  $<%= (r.goal_in_cents.to_f/100).round %></br>
  <%= r.start_date %></br>
  <%= r.end_date %></br>
<% end %>

app/views/projects/show.html.erb
<% if current_user != nil %>
  <% if session[:user_id] == @project.user_id %>
    <h3><%= current_user.username %>'s Owner Console</h3>
    <%= link_to "Edit This Project", edit_project_path %> | 
    <%= link_to "Delete This Project", @project, method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
<% end %>

<h2><%= @project.title %></h2></br>
<%= image_tag @project.photo %></br></br>
<%= @project.description %></br>
Goal: $<%= (@project.goal_in_cents.to_f / 100) %></br>
Start Date: <%= @project.start_date %></br>
End Date: <%= @project.end_date %></br>
<%= @days_left %> Days Left</br>
Pledges so far: $<%= @total.to_f / 100 %></br></br>

<h3> Pledges </h3>
  <div id="pledge-list">
    <%= render "showpledge" %>
  </div>
</br>

<% if current_user %>
  <a href="#" data-reveal-id="pledgeModal" class="radius button">I Want to Pledge!</a>
  <div id="pledgeModal" class="reveal-modal" data-reveal>
    <%= render "pledgeform" %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

</br>

<h3> Comments </h3>
  <div id="discussion-list">
    <%= render :partial => "showcomment" %>
  </div>
</br>

<% if current_user %>
  <a href="#" data-reveal-id="commentModal" class="radius button">Add a Comment</a>
  <div id="commentModal" class="reveal-modal" data-reveal>
    <%= render "commentform" %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

app/views/projects/show.js.erb
$('body').append("<%= escape_javascript(render @project) %>");