config/routes.rb
Microaccel::Application.routes.draw do

root 'projects#index'

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "users#new", :as => "signup"

resources :projects do
  resources :discussions, :except => [:index]
  resources :pledges
end

resources :users
resources :sessions

get 'tags/:tag', to: 'projects#index', as: :tag

get '/search', to: 'projects#search', as: 'search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MicroAccel" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <!-- Navigation -->
<div class="fixed">
 <div class="contain-to-grid">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <%= link_to "MicroAccel", projects_path %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
 
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>
          <li class="active">
            <%= link_to current_user.email, user_path(current_user.id) %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "LOG OUT", logout_path %>
          </li>
          <li class="divider"></li>
        <% else %>
          <li class="inactive">
            <%= link_to "LOG IN", login_path %>
          </li>
          <li class="active">
            <%= link_to "SIGN UP", signup_path %>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>
</div>
 
  <!-- End Top Bar -->


      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>